title: Middletown
lang: cs
twitter:
facebook: https://www.facebook.com/otevrenamesta
gitlab: https://gitlab.com/otevrenamesta
github: https://github.com/otevrenamesta
instagram:
cdn: https://modurad.otevrenamesta.cz/media/omstredni
cdnapi: https://modurad.otevrenamesta.cz/cdn
profileURL: https://modurad.otevrenamesta.cz/omstredni/auth/profile
api: https://modurad.otevrenamesta.cz/omstredni
menu:
- label: Radnice
  link: "/radnice/"
- label: Volný čas
  link: "/volny-cas/"
- label: Projekty
  link: /projekty
globalComponents:
  - breadCrumbs
  - paginator
apps:
  - path: /novinky/
    module: ./components/detailPage/post.js
    url: api
    template: page
