title: Middletown
lang: cs
twitter:
facebook: https://www.facebook.com/otevrenamesta
gitlab: https://gitlab.com/otevrenamesta
github: https://github.com/otevrenamesta
instagram:
cdn: https://modurad.otevrenamesta.cz/media/omstredni
cdnapi: https://modurad.otevrenamesta.cz/cdn
profileURL: https://modurad.otevrenamesta.cz/omstredni/auth/profile
api: https://modurad.otevrenamesta.cz/omstredni
menu:
- label: Radnice
  link: "/radnice/"
- label: Volný čas
  link: "/volny-cas/"
- label: Projekty
  link: /projekty
globalComponents:
  breadCrumbs: breadCrumbs
  paginator: paginator
apps:
  # - path: /novinky/
  #   module: ./detailPage/post.js
  #   url: api
  #   template: page
  - path: /paro/
    title: Participativní rozpočet
    module: https://modurad.otevrenamesta.cz/adminmodules/bbb-paro/index.js
    templates: https://modurad.otevrenamesta.cz/adminmodules/bbb-paro/layouts/bulma/
    layout: page
    url: https://modurad.otevrenamesta.cz/omstredni/paro/
