title: Middletown
lang: cs
twitter:
facebook: https://www.facebook.com/otevrenamesta
gitlab: https://gitlab.com/otevrenamesta
github: https://github.com/otevrenamesta
instagram:
cdn: https://modurad.otevrenamesta.cz/media/omstredni
cdnapi: https://modurad.otevrenamesta.cz/cdn
menu:
- label: Radnice
  link: "/radnice/"
- label: Volný čas
  link: "/volny-cas/"
- label: Projekty
  link: /projekty
globalComponents:
  - breadCrumbs
  - paginator
detailpages:
  - path: /novinky/:id
    component: ./components/detailPage/post.js
  - path: /kalendar/:id
    component: ./components/detailPage/kalendar.js
  - path: /formulare/:id
    component: ./components/detailPage/form.js
    # children:
    #   - component: newestItemsText
    #     title: podobne clanky
    #     pocet: 5
    #     url: /api/uni/posts/
  - path: /formulare
    component: ./components/listPage/form.js
